Environment:
    cluster: Minerva
    server: 
project_directory: /home/immanuel/Documents/Develop/SPEctRA_test_environment/proj_dir
Short-read_aligners:
    tophat2: tophat2/version
    bowtie2: bowtie2/version
    STAR: STAR/version
genomes: 
    mouse: 
        rRNApath: /path/to/rRNA/gtf
        tophat2: 
            gtf: 
            index: /path/to/tophat2/genome/
        geneLenghts: /path/to/gene/length/file
        STAR:
            path: 
