Environment:
    cluster: 
    server: local
project_directory: /path/to/project/directory/
Short-read_aligners:
    tophat2: tophat2/version
    bowtie2: bowtie2/version
    STAR: STAR/version
genomes: 
    mouse: 
        rRNApath: /path/to/rRNA/gtf
        tophat2: 
            gtf: /path/to/genome/annotation
            index: /path/to/tophat2/genome/
        exonicPath: 
        intronicPath: 
        intragenicPath:
        intergenicPath:
        STAR:
            path: 
    hg19_ERCC: 
        rRNApath: 
        tophat2:  
            gtf: 
            index: 
        exonicPath: 
        intronicPath:
        intragenicPath:
        intergenicPath:
        STAR:
            path:
    mm9: 
        rRNApath: 
        tophat2:  
            gtf: 
            index: 
        exonicPath: 
        intronicPath: 
        intragenicPath:
        intergenicPath:
        STAR:
            path: 